//package Exception;
// provide error
//class TryCatchFinally4
//{
//    public static void main(String[] args)
//    {
//        System.out.println("1");
//
//        try
//        {
//            System.out.println(100/0);
//            System.out.println("2");
//        }
//        //System.out.println("hi");
//        catch(Exception e)
//        {
//            System.out.println("3");
//        }
//        System.out.println("hi");
//		finally
//        {
//            System.out.println("4");
//        }
//
//        System.out.println("5");
//    }
//}